# -*- coding: utf-8 -*-
"""DogBreedClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UTASmspFP-TUn_V1_jes-No95vLIXuH
"""

#!unzip "/content/drive/MyDrive/Dog-vision/dog-breed-identification.zip" -d "/content/drive/MyDrive/Dog-vision/"

"""from io import BufferedReader
#End-to -end multi class Dog Breed classification
using Tensorflow 2.17.1

# 1. Problem
  Identify the breed of the dog from the given Image.

# 2. Data
  We're using data from kaggle's dog breed identification competition.

# 3. Evaluation
  The evaluation is a file that contains probability of each dog breed for each test image.

# 4. Features
  * The data have 120 different dog breeds
  * We've around 10,000+ images in train set.
  * We've around 10,000+ images in test set.
"""

import tensorflow as tf
import tensorflow_hub as hub
print("TF version", tf.__version__)
print("Hub version", hub.__version__)

print("GPU", "available (YESS!!)" if tf.config.list_physical_devices("GPU") else ("not available:("))

"""# Turning the data into Tensors"""

import pandas as pd
label_csv = pd.read_csv("/content/drive/MyDrive/Dog-vision/labels.csv")
print(label_csv.describe())
print(label_csv.head())

label_csv['breed'].value_counts().plot.bar(figsize=(20,10))

label_csv["breed"].value_counts().median()

from IPython.display import Image
Image("/content/drive/MyDrive/Dog-vision/train/001513dfcb2ffafc82cccf4d8bbaba97.jpg")

"""# Getting Images and their labels"""

label_csv.head()

filenames=["/content/drive/MyDrive/Dog-vision/train/" + fname + ".jpg" for fname in label_csv['id']]
filenames[:10]

import os
if len(os.listdir("/content/drive/MyDrive/Dog-vision/train/")) == len(filenames):
  print("Filenames match actual amount of file . Proceed.")
else:
  print("Filenames do not match the actual number of files. Check gthe atrget directory.")

Image(filenames[5000])

label_csv["breed"][5000]

import numpy as np
labels = label_csv["breed"].to_numpy()
#labels = np.array(labels)
labels

if len(labels)== len(filenames):
  print("Number of labels matches the number of filenames")
else:
  print("Number of labels does not matches the number of filenames , check the data dictionaries")

unique_breeds = np.unique(labels)
unique_breeds

print(labels[0])
labels[0]==unique_breeds

boolean_labels= [label == unique_breeds for label in labels]
boolean_labels[:2]

len(boolean_labels)

Image(filenames[20])

print(labels[20])
print(np.where(unique_breeds== labels[20]))
print(boolean_labels[20].argmax())
print(boolean_labels[20].astype(int))

"""# Creating our own validation set"""

# Setting X & y variables
X= filenames
y= boolean_labels

len(filenames)

#Start with ~1000 images and increase as per need
NUM_IMAGES = 1000 #@param {type:"slider", min:1000, max:10000 , step:1000}

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val =train_test_split(X[:NUM_IMAGES],
                                                 y[:NUM_IMAGES],
                                                 test_size=0.2,
                                                 random_state=42)
len(X_train), len(X_val), len(y_train), len(y_val)

X_train[:2], y_train[:2]

"""## Preprocessing Images(Images into tensors)"""

from matplotlib.pyplot import imread
image= imread(filenames[30])
image.shape

image.max(), image.min()

image[:2]

tf.constant(image)[:2]

IMG_SIZE = 224
def process_image(image_path, img_size=IMG_SIZE):
   #read the image file
   image= tf.io.read_file(image_path)
   #turn the jpeg to numerical tensor with three color channels
   image= tf.image.decode_jpeg(image, channels=3)
   #turn the color channel values from 0-255 to 0-1 values
   image = tf.image.convert_image_dtype(image, tf.float32)
   #Resize the image
   image = tf.image.resize(image, size=[img_size,img_size])

   return image

image_path = filenames[40]

image = tf.io.read_file(image_path)
image

image= tf.image.decode_jpeg(image, channels=3)
image

image= tf.image.convert_image_dtype(image, tf.float32)
image

"""## Turning our data into batches"""

def get_image_label(image_path,label):
  image= process_image(image_path)
  return image, label

(process_image(X[42]), y[42])

#define teh batch size
BATCH_SIZE= 32

def create_data_batches(X, y=None, batch_size=BATCH_SIZE, valid_data=False, test_data=False):
  if test_data:
    print("Creating test data batches...")
    data = tf.data.Dataset.from_tensor_slices((tf.constant(X)))
    data_batch= data.map(process_image).batch(batch_size)
    return data_batch
  elif valid_data:
    print("Creating validation data batches...")
    data = tf.data.Dataset.from_tensor_slices((tf.constant(X), tf.constant(y)))
    data_batch=data.map(get_image_label).batch(batch_size)
    return data_batch

  else:
    print("Creating validation data batches...")
    data = tf.data.Dataset.from_tensor_slices((tf.constant(X), tf.constant(y)))
    data = data.shuffle(buffer_size=len(X))
    #create (image, label) tuples and also preprocesses the data
    data =data.map(get_image_label)
    data_batch=data.batch(batch_size)

  return data_batch

train_data= create_data_batches(X_train, y_train)
val_data= create_data_batches(X_val, y_val, valid_data=True)

train_data.element_spec, val_data.element_spec

"""## Visualizing Data Batches"""

import matplotlib.pyplot as plt

def show_25_images(images, labels):

  plt.figure(figsize=(10,10))

  for i in range(25):
    ax =plt.subplot(5,5,i+1)
    plt.imshow(images[i])
    plt.title(unique_breeds[labels[i].argmax()])
    plt.tight_layout()
    plt.axis("off")

train_images, train_labels= next(train_data.as_numpy_iterator())

len(train_images), len(train_labels)

show_25_images(train_images, train_labels)

val_images, val_labels= next(val_data.as_numpy_iterator())
show_25_images(val_images, val_labels)

"""
## Building a model
Before building the model we need to define:
* The input shape to our model.
* The output shape to our model.
* The URL ogf the model we want to use."""

INPUT_SHAPE = [None,IMG_SIZE, IMG_SIZE, 3 ] #batch , h, w, colour channels

OUTPUT_SHAPE = len(unique_breeds)

MODEL_URL = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4"

# def create_model(input_shape= INPUT_SHAPE, output_shape= OUTPUT_SHAPE, model_url= MODEL_URL):

#   print("Building model with:", MODEL_URL)

#   model= tf.keras.Sequential([
#       hub.KerasLayer(MODEL_URL),
#       tf.keras.layers.Dense(units=OUTPUT_SHAPE,
#                             activation="softmax")
#   ])

#   #Compile model

#   model.compile(loss=tf.keras.losses.CategoricalCrossentropy(),
#                 optimizer=tf.keras.optimizers.Adam(),
#                 metrics=["accuracy"])

#   model.build(INPUT_SHAPE)

#   return model

# model = create_model()
# model.summary()
# Use TF Hub's MobileNetV2 with proper preprocessing
import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model

# Constants
INPUT_SHAPE = (224, 224, 3)  # MobileNetV2's expected input
OUTPUT_SHAPE = 120  # Number of classes

# ----------------------------------------------
# Build Model with Preprocessing
# ----------------------------------------------
def build_model():
    # Load MobileNetV2 with pre-trained weights (no top)
    base_model = MobileNetV2(
        input_shape=INPUT_SHAPE,
        include_top=False,  # Remove the original classification layer
        weights='imagenet'
    )

    # Freeze base model
    base_model.trainable = False

    # Add new layers
    inputs = tf.keras.Input(shape=INPUT_SHAPE)
    x = base_model(inputs, training=False)
    x = GlobalAveragePooling2D()(x)
    outputs = Dense(OUTPUT_SHAPE, activation="softmax")(x)

    # Compile
    model = Model(inputs, outputs)
    model.compile(
        optimizer="adam",
        loss="categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

# Create and test
model = build_model()
model.summary()

"""## Creating Callbacks

"""

# Commented out IPython magic to ensure Python compatibility.

# %load_ext tensorboard

import datetime

def create_tensorboard_callbavks():
  logdir= os.path.join("/content/drive/MyDrive/Dog-vision/logs",
                       datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
  return tf.keras.callbacks.TensorBoard(logdir)

early_stopping= tf.keras.callbacks.EarlyStopping(monitor="val_accuracy",
                                                  patience=3)

## Training on Subset of data(1000)

NUM_EPOCHS= 100 #@param {type:"slider", min:10, max:100, step:10}

def train_model():
  model= build_model()

  tensorboard= create_tensorboard_callbavks()

  model.fit(x=train_data,
            epochs=NUM_EPOCHS,
            validation_data=val_data,
            validation_freq=1,
            callbacks=[tensorboard, early_stopping])
  return model

model= train_model()

### Checking the tensorboard logs

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir /content/drive/MyDrive/Dog-vision/logs

## Making and evaluating predictions using trained model

val_data

predictions =model.predict(val_data, verbose=1)

predictions

predictions.shape

len(y_val)

index= 87
print(predictions[index])
print(f"Max vaue(prob of predictions): {np.max(predictions[index])}")
print(f"Sum: {np.sum(predictions[index])}")
print(f"Max index: {np.argmax(predictions[index])}")
print(f"Predicted label: {unique_breeds[np.argmax(predictions[index])]}")

#Note : prediction probabilities are also called confidence label

def get_pred_label(pred_probabilities):
  """
  Turn a array of prediction probabilities into a label.
  """
  return unique_breeds[np.argmax(pred_probabilities)]

pred_label= get_pred_label(predictions[56])
pred_label

"""# Create a function to unbatch a batch dataset"""

def unbatchify(data):
   images = []
   labels = []

   for image, label in val_data.unbatch().as_numpy_iterator():
       images.append(image)
       labels.append(unique_breeds[np.argmax(label)])
   return images, labels

val_images, val_labels = unbatchify(val_data)
val_images[0], val_labels[0]

# images = []
# labels = []

# for image, label in val_data.unbatch.as_numpy_iterator():
#   images.append(image)
#   labels.append(label)

# images[0], labels[0]

"""Create a function that will take an array pf pred probabilities , an array of truth labels and an array of arrays and integers"""

def plot_pred(pred_probabilities, labels , images, n=1):
  pred_prob, true_label, image= pred_probabilities[n], labels[n], images[n]

  pred_label= get_pred_label(pred_prob)

  plt.imshow(image)
  plt.xticks([])
  plt.yticks([])

  if pred_label ==true_label:
    color="green"
  else:
    color="red"

  plt.title("{} {:2.0f}%  {}".format(pred_label,
                                      np.max(pred_prob)*100,
                                      true_label), color= color)

plot_pred(pred_probabilities= predictions,
          labels=val_labels,
          images=val_images)

def plot_pred_conf(pred_probabilities, labels, n=1):
  pred_prob, true_label= pred_probabilities[n], labels[n]

  pred_label= get_pred_label(pred_prob)

  top_10_pred_indexes= pred_prob.argsort()[-10:][::-1]

  top_10_pred_values= pred_prob[top_10_pred_indexes]
  top_10_pred_labels= np.array(unique_breeds)[top_10_pred_indexes]

  top_10_pred_labels= unique_breeds[top_10_pred_indexes]

  top_plot= plt.bar(np.arange(len(top_10_pred_labels)),
                    top_10_pred_values,
                    color= "grey")

  plt.xticks(np.arange(len(top_10_pred_labels)),
             labels= top_10_pred_labels,
             rotation="vertical")

  if np.isin(true_label, top_10_pred_labels):
    top_plot[np.argmax(top_10_pred_labels==true_label)].set_color("green")
  else:
    pass

plot_pred_conf(pred_probabilities= predictions,
              labels=val_labels,
               n=8)

i_multiplier= 0
num_rows = 3
num_cols=2
num_images= num_rows * num_cols
plt.figure(figsize=(10* num_cols, 5*num_rows))
for i in range(num_images):
  plt.subplot(num_rows, 2*num_cols, 2*i+1)
  plot_pred(pred_probabilities= predictions,
            labels= val_labels,
            images= val_images,
            n=i+i_multiplier)
  plt.subplot(num_rows, 2*num_cols, 2*i+2)
  plot_pred_conf(pred_probabilities= predictions,
                 labels= val_labels,
                 n=i+i_multiplier)
plt.tight_layout(h_pad=1.0)
plt.show()

## Saving the model

def save_model(model, suffix=None):

  modeldir= os.path.join("/content/drive/MyDrive/Dog-vision/models",
                         datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
  model_path= modeldir + "-" + suffix + ".keras"
  print(f"Saving model to: {model_path}...")
  model.save(model_path)
  return model_path

# def load_trained_model(model_path):
#   print(f"Loading saved model from: {model_path}")
#   model= load_model(model_path)
#   return model

save_model(model, suffix= "1000-images-mobilenetv2-Adam")

from keras.models import load_model  # Import the correct function

def load_trained_model(model_path):  # Rename function to avoid recursion error
    print(f"Loading saved model from: {model_path}")
    model = load_model(model_path)  # Calls TensorFlow's load_model correctly
    return model

# Call the function
loaded_1000_image_model = load_trained_model("/content/drive/MyDrive/Dog-vision/models/20250217-135416-1000-images-mobilenetv2-Adam.keras")

loaded_1000_image_model.evaluate(val_data)



"""## Training a dog model on full dataset"""

len(X), len(y)

from PIL import Image
import os

def remove_corrupt_images(image_paths, labels):
    clean_image_paths = []
    clean_labels = []

    for img_path, label in zip(image_paths, labels):
        try:
            # Try opening the image
            img = Image.open(img_path)
            img.verify()  # Verify image integrity
            clean_image_paths.append(img_path)
            clean_labels.append(label)
        except (IOError, SyntaxError):
            print(f"Corrupt file removed: {img_path}")

    return clean_image_paths, clean_labels

# Remove corrupted images before batching
X_clean, y_clean = remove_corrupt_images(X, y)

# Now create batches
full_data = create_data_batches(X_clean, y_clean)

# full_data= create_data_batches(X,y)
full_data

full_model= build_model()

full_model_tensorboard= create_tensorboard_callbavks()

full_model_early_stopping = tf.keras.callbacks.EarlyStopping(monitor= "accuracy",
                                                             patience=3)

import os
print(os.path.exists("/content/drive/MyDrive/Dog-vision/train/a7f9839ac0a874686eb418d317eae284.jpg"))

full_model.fit(x=full_data,
              epochs=NUM_EPOCHS,
              callbacks=[full_model_tensorboard, full_model_early_stopping])

save_model(full_model, suffix= "full-dataset-mobilenetv2-Adam")

"""## Making prediction on test dataset"""

# test_path= "/content/drive/MyDrive/Dog-vision/test"
# test_filenames= [test_path + fname for fname in os.listdir(test_path)]
# test_filenames[:10]

import os

test_path = "/content/drive/MyDrive/Dog-vision/test"

# Get all filenames with the correct path
test_filenames = [os.path.join(test_path, fname) for fname in os.listdir(test_path)]

# Remove missing or corrupted files before batching
def filter_missing_files(file_paths):
    valid_paths = [path for path in file_paths if os.path.exists(path)]
    removed_files = set(file_paths) - set(valid_paths)

    if removed_files:
        print(f" Removed {len(removed_files)} missing images.")

    return valid_paths

# Clean test filenames
test_filenames_clean = filter_missing_files(test_filenames)

test_data = create_data_batches(test_filenames_clean, test_data=True)

test_data

loaded_full_model=load_trained_model("/content/drive/MyDrive/Dog-vision/models/20250218-124402-full-dataset-mobilenetv2-Adam.keras")

test_predictions =loaded_full_model.predict(test_data, verbose=1)

test_loss, test_acc = loaded_full_model.evaluate(test_data)
print(f"Test Accuracy: {test_acc:.4f}")

#save predictions to csv file (for access later)
np.savetxt("/content/drive/MyDrive/Dog-vision/preds_array.csv", test_predictions, delimiter=",")

test_predictions= np.loadtxt("/content/drive/MyDrive/Dog-vision/preds_array.csv", delimiter=",")

test_predictions[:10]

"""# Preparing test dataset predictions for kaggle"""

preds_df= pd.DataFrame(columns=["id"]+ list(unique_breeds))
preds_df.head()

#Append test image ID's to predictions DataFrame
test_ids= [os.path.splitext(path)[0] for path in os.listdir(test_path)]
preds_df["id"]= test_ids
preds_df.head()

preds_df[list(unique_breeds)] = test_predictions
preds_df.head()

preds_df.to_csv("/content/drive/MyDrive/Dog-vision/full_model_preds_submission_1_mobilenetV2.csv", index= False)

"""#Making Predictions on custom data"""

custom_path="/content/drive/MyDrive/Dog-vision/myDogPhotos/"
custom_images_paths= [os.path.join(custom_path, fname) for fname in os.listdir(custom_path)]
custom_images_paths

custom_data= create_data_batches(custom_images_paths, test_data=True)
custom_data

custom_preds =loaded_full_model.predict(custom_data)

custom_preds.shape

custom_pred_labels =[get_pred_label(custom_preds[i]) for i in range(len(custom_preds))]
custom_pred_labels

custom_images= []

for image in custom_data.unbatch().as_numpy_iterator():
  custom_images.append(image)

plt.figure(figsize=(10,10))

for i, image in enumerate(custom_images):
  plt.subplot(1, 3, i+1)
  plt.xticks([])
  plt.yticks([])
  plt.title(custom_pred_labels[i])
  plt.imshow(image)

